import './globals.css'
import { Inter, Exo_2, Open_Sans } from 'next/font/google'

const inter = Inter({
   subsets: ['latin'],
   display: 'swap',
   variable: '--font-inter',
  })

const exo = Exo_2({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-exo',
 })
const openSans = Open_Sans({ 
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-openSans',
 })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${exo.variable} ${openSans.variable} `}>{children}</body>
    </html>
  )
}
